version: "2"

services:
  node:
    image: "node:8.14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "node task.js"

## docker-compose run node node task.js